### ISSUE TITLE
Which version of eveliver did you use? How to avoid the following issue?

### ISSUE THREAD

**Issue by WatsonWangZh** [thunlp/CodRED#4]
python codred-blend.py --train --dev --per_gpu_train_batch_size 1 --per_gpu_eval_batch_size 1 --learning_rate 3e-5 --num_workers 2 --logging_step 10

2022-04-08 22:13:30.272958: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
INFO:root:Process rank: -1, device: cuda, n_gpu: 1, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "codred-blend.py", line 498, in <module>
    main()
  File "codred-blend.py", line 494, in main
    trainer.run()
  File "/.local/lib/python3.6/site-packages/eveliver/trainer.py", line 381, in run
    self.load_data()
  File "/.local/lib/python3.6/site-packages/eveliver/trainer.py", line 322, in load_data
    train_dataset, dev_dataset, test_dataset = self.callback.load_data()
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by yaoyuanTHU** [comment]
As indicated by the README, it should be "pip install eveliver==1.21.0"
